
services:
  nginx:
    image: nginx:stable
    container_name: nginx-tor
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: tor
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge